from selenium import webdriver
from selenium.webdriver.firefox.options import Options
import time
from pygame import mixer
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
import threading

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dyn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(64, 131, 203)")
        self.label_titulo = QtWidgets.QLabel(Dialog)
        self.label_titulo.setGeometry(QtCore.QRect(290, 0, 210, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(185, 40, 430, 261))
        self.label_2.setStyleSheet("background-color: white")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_login = QtWidgets.QLabel(Dialog)
        self.label_login.setGeometry(QtCore.QRect(360, 40, 70, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("background-color: white")
        self.label_login.setObjectName("label_login")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(270, 90, 251, 31))
        self.lineEdit_email.setStyleSheet("background-color: rgb(233, 237, 238);border: 2px solid rgb(233, 237, 238); padding: 1px; border-style: solid; border-radius: 8px")
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_senha = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_senha.setGeometry(QtCore.QRect(270, 130, 251, 31))
        self.lineEdit_senha.setStyleSheet("background-color: rgb(233, 237, 238);border: 2px solid rgb(233, 237, 238); padding: 1px; border-style: solid; border-radius: 8px")
        self.lineEdit_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.lineEdit_link = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_link.setGeometry(QtCore.QRect(270, 170, 251, 31))
        self.lineEdit_link.setStyleSheet("background-color: rgb(233, 237, 238);border: 2px solid rgb(233, 237, 238); padding: 1px; border-style: solid; border-radius: 8px")
        self.lineEdit_link.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.btn_entrar = QtWidgets.QPushButton(Dialog)
        self.btn_entrar.setGeometry(QtCore.QRect(270, 250, 251, 41))
        self.btn_entrar.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 8px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.btn_entrar.setObjectName("btn_entrar")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(185, 310, 430, 241))
        self.label_4.setStyleSheet("background-color: white")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.btn_iniciar = QtWidgets.QPushButton(Dialog)
        self.btn_iniciar.setGeometry(QtCore.QRect(270, 400, 251, 41))
        self.btn_iniciar.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 8px;border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2198c0, stop: 1 #0d5ca6);}QPushButton:pressed { background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #0d5ca6, stop: 1 #2198c0);")
        self.btn_iniciar.setObjectName("btn_iniciar")
        self.label_posts = QtWidgets.QLabel(Dialog)
        self.label_posts.setGeometry(QtCore.QRect(300, 340, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_posts.setFont(font)
        self.label_posts.setStyleSheet("background-color: white")
        self.label_posts.setObjectName("label_posts")
        self.label_erro = QtWidgets.QLabel(Dialog)
        self.label_erro.setGeometry(QtCore.QRect(300, 450, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_erro.setFont(font)
        self.label_erro.setAutoFillBackground(False)
        self.label_erro.setStyleSheet("background-color: white; color: red")
        self.label_erro.setObjectName("label_erro")
        self.label_posts_valor = QtWidgets.QLabel(Dialog)
        self.label_posts_valor.setGeometry(QtCore.QRect(400, 340, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_posts_valor.setFont(font)
        self.label_posts_valor.setStyleSheet("background-color: white")
        self.label_posts_valor.setObjectName("label_posts_valor")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 151, 241))
        self.label_5.setStyleSheet("background-color: white")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_aviso = QtWidgets.QLabel(Dialog)
        self.label_aviso.setGeometry(QtCore.QRect(60, 40, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_aviso.setFont(font)
        self.label_aviso.setStyleSheet("background-color: white")
        self.label_aviso.setObjectName("label_aviso")
        self.label_aviso1 = QtWidgets.QLabel(Dialog)
        self.label_aviso1.setGeometry(QtCore.QRect(30, 75, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_aviso1.setFont(font)
        self.label_aviso1.setStyleSheet("color: white")
        self.label_aviso1.setObjectName("label_aviso1")
        self.label_aviso2 = QtWidgets.QLabel(Dialog)
        self.label_aviso2.setGeometry(QtCore.QRect(30, 90, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_aviso2.setFont(font)
        self.label_aviso2.setStyleSheet("color: white")
        self.label_aviso2.setObjectName("label_aviso2")
        self.label_aviso3 = QtWidgets.QLabel(Dialog)
        self.label_aviso3.setGeometry(QtCore.QRect(30, 105, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_aviso3.setFont(font)
        self.label_aviso3.setStyleSheet("color: white")
        self.label_aviso3.setObjectName("label_aviso3")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(30, 120, 131, 151))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.lineEdit_posts = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_posts.setGeometry(QtCore.QRect(270, 210, 121, 31))
        self.lineEdit_posts.setStyleSheet("background-color: rgb(233, 237, 238);border: 2px solid rgb(233, 237, 238); padding: 1px; border-style: solid; border-radius: 8px")
        self.lineEdit_posts.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_posts.setObjectName("lineEdit_posts")

        self.lineEdit_time = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_time.setGeometry(QtCore.QRect(400, 210, 121, 31))
        self.lineEdit_time.setStyleSheet("background-color: rgb(233, 237, 238);border: 2px solid rgb(233, 237, 238); padding: 1px; border-style: solid; border-radius: 8px")
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "futBot v1.1"))
        self.label_titulo.setText(_translate("Dialog", "MVGIC futBot v1.1"))
        self.label_login.setText(_translate("Dialog", "Login"))
        self.lineEdit_email.setPlaceholderText(_translate("Dialog", "email"))
        self.lineEdit_senha.setPlaceholderText(_translate("Dialog", "senha"))
        self.lineEdit_link.setPlaceholderText(_translate("Dialog", "link da partida"))
        self.btn_entrar.setText(_translate("Dialog", "ENTRAR"))
        self.btn_iniciar.setText(_translate("Dialog", "INICIAR O BOT"))
        self.label_posts.setText(_translate("Dialog", "POSTS: "))
        self.label_erro.setText(_translate("Dialog", "Partida não localizada!"))
        self.label_posts_valor.setText(_translate("Dialog", "190"))
        self.label_aviso.setText(_translate("Dialog", "AVISO"))
        self.label_aviso1.setText(_translate("Dialog", "Não clicar várias vezes"))
        self.label_aviso2.setText(_translate("Dialog", "seguidas nos botões"))
        self.label_aviso3.setText(_translate("Dialog", "para evitar crash"))
        self.lineEdit_posts.setPlaceholderText(_translate("Dialog", "posts"))
        self.lineEdit_time.setPlaceholderText(_translate("Dialog", "tempo"))


        self.label_erro.hide()
        self.label_posts_valor.hide()
        self.lineEdit_senha.setEchoMode(QtWidgets.QLineEdit.Password)

        self.btn_entrar.clicked.connect(self.logar)
        self.btn_iniciar.clicked.connect(self.initd)

    def logar(self):
        global driver
        options = Options()
        options.headless = True
        driver = webdriver.Firefox()  # seu path do driver
        driver.get('https://futwebapp.com.br/estadios/criarPartida/1')

        driver.find_element_by_name('email').send_keys(self.lineEdit_email.text())
        driver.find_element_by_name('password').send_keys(self.lineEdit_senha.text())
        driver.find_element_by_xpath('/html/body/div/section/div/div/div/div/form/center/button').click()
        self.btn_entrar.setDisabled(True)
        self.btn_entrar.setStyleSheet("font: 15pt Arial;margin: 1px; border-color: #0c457e; border-style: outset; border-radius: 8px;"
                                      "border-width: 1px;color: white;background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #A9A9A9, stop: 1 #D3D3D3)}")
        time.sleep(3)
        driver.get(self.lineEdit_link.text())


    def initd(self):
        t = threading.Thread(target=self.iniciar)
        t.start()

    def logartd(self):
        t2 = threading.Thread(target=self.logar)
        t2.start()

    def iniciar(self):
        self.label_erro.hide()
        self.label_posts_valor.show()
        self.label_posts_valor.setText("0")
        cont = 0

        try:
            for i in range(int(self.lineEdit_posts.text())):
                driver.find_element_by_id('ball').click()
                cont+=1
                self.label_posts_valor.setText(str(cont))
                if (isinstance(int(self.lineEdit_time.text(), (int))) == True):
                    time.sleep(int(self.lineEdit_time.text()))

            self.label_erro.setText('Partida finalizada!')
            self.label_erro.setStyleSheet('color: green; background-color: white')
            self.label_erro.show()
            mixer.init()
            mixer.music.load('win.mp3')
            mixer.music.play()

        except:
            self.label_erro.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

